const dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');
window.addEventListener('mousemove',e=>{dot.style.left=ring.style.left=e.clientX+'px';dot.style.top=ring.style.top=e.clientY+'px'});
document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('hover'));el.addEventListener('mouseleave',()=>ring.classList.remove('hover'))});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.15});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('.resume-link').forEach(el=>el.addEventListener('click',()=>document.querySelector('.resume-modal').classList.add('open')));
document.querySelector('.close-modal').addEventListener('click',()=>document.querySelector('.resume-modal').classList.remove('open'));
document.querySelector('.resume-modal').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.classList.remove('open')});
const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');
const glitter={particleCount:289,colors:['#E4E309','#FFFFFF','#CAE00B'],speed:2,density:74,starSize:16,focalDepth:6,brightness:.61,intensity:2};
let stars=[],glitterSize={w:0,h:0,dpr:1},last=performance.now(),elapsed=0;
function makeStar(initial=true){const a=Math.random()*Math.PI*2,r=(.2+Math.random()*.8)*(glitter.density/15);return{x:Math.cos(a)*r,y:Math.sin(a)*r,z:initial?Math.random():1,px:NaN,py:NaN,v:.6+Math.random()*.8,color:Math.floor(Math.random()*3),next:elapsed+1+Math.random()*2,flash:0}}
function reset(s){Object.assign(s,makeStar(false))}
function resizeGlitter(){const dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(w===glitterSize.w&&h===glitterSize.h&&dpr===glitterSize.dpr)return;glitterSize={w,h,dpr};canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h)}
function glitterLoop(t){const dt=Math.min(.1,Math.max(.001,(t-last)/1000))*60;last=t;elapsed+=dt/60;const{w,h}=glitterSize,cx=w/2,cy=h/2,scale=Math.min(w,h)*.9,focal=glitter.focalDepth/100;ctx.globalCompositeOperation='destination-out';ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='lighter';for(const s of stars){s.z-=glitter.speed*.0008*s.v*dt;if(s.z<=focal){reset(s);continue}const p=focal/Math.max(s.z,.0001),sx=cx+s.x*p*scale,sy=cy+s.y*p*scale;if(sx<-25||sx>w+25||sy<-25||sy>h+25){reset(s);continue}if(elapsed>s.next&&elapsed>s.flash){s.flash=elapsed+.05+Math.random()*.06;s.next=elapsed+1+Math.random()*3}const flashing=elapsed<s.flash,near=1-s.z,r=Math.min((glitter.starSize*.15)*(.4+Math.min(2.5,p*.6))*(flashing?1.5:1),1+glitter.starSize*.375);const alpha=Math.min(1,(near*.9+.06)*glitter.brightness*(flashing?1:.82));ctx.strokeStyle=glitter.colors[s.color];ctx.fillStyle=glitter.colors[s.color];if(!Number.isNaN(s.px)){ctx.globalAlpha=alpha*.35;ctx.lineWidth=Math.max(.35,r*.35);ctx.beginPath();ctx.moveTo(s.px,s.py);ctx.lineTo(sx,sy);ctx.stroke()}ctx.globalAlpha=alpha;ctx.fillRect(sx-r,sy-r,r*2,r*2);if(flashing){ctx.globalAlpha=alpha*.45;ctx.fillRect(sx-r*1.9,sy-r*.18,r*3.8,r*.36);ctx.fillRect(sx-r*.18,sy-r*1.9,r*.36,r*3.8)}s.px=sx;s.py=sy}ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';requestAnimationFrame(glitterLoop)}
stars=Array.from({length:glitter.particleCount},()=>makeStar());resizeGlitter();addEventListener('resize',resizeGlitter);requestAnimationFrame(glitterLoop);
